version: '3'
services:
  zookeeper:
    ports:
      - "2181:2181"

  broker:
    environment:
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
    ports:
      - "9092:9092"
      - "29092:29092"

  schema-registry:
    ports:
      - "8081:8081"

  rest-proxy:
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: 'broker:9092'
    ports:
      - "8082:8082"

