---
version: 2

references:
  repo_cache_key: &repo_cache_key
    v1-jackdaw-{{ .Branch }}-{{ .Revision }}

  repo_cache_backup_1: &repo_cache_backup_1
    v1-jackdaw-{{ .Branch }}

  repo_cache_backup_2: &repo_cache_backup_2
    v1-jackdaw

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - *repo_cache_key
        - *repo_cache_backup_1
        - *repo_cache_backup_2

  mvn_cache_key: &mvn_cache_key
    v1-jackdaw-deps-{{ checksum "project.clj" }}

  mvn_cache_backup: &mvn_cache_backup
    v1-jackdaw-deps

  restore_mvn: &restore_mvn
    restore_cache:
      keys:
        - *mvn_cache_key
        - *mvn_cache_backup

  build_config: &build_config
    docker:
      - image: circleci/clojure:lein-2.8.1
    working_directory: /home/circleci/jackdaw

  test_config: &test_config
    docker:
      - image: docker/compose:1.23.2
    working_directory: /home/circleci/jackdaw

jobs:
  checkout_code:
    <<: *build_config
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: v1-jackdaw-{{ .Branch }}-{{ .Revision }}
          paths:
            - .
  deps:
    <<: *build_config
    steps:
      - *restore_repo
      - *restore_mvn
      - run:
          lein with-profiles +test deps
      - save_cache:
          key: *mvn_cache_key
          paths:
            - /home/circleci/.m2
  build:
    <<: *test_config
    steps:
      - *restore_repo
      - *restore_mvn
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          docker-compose up -d
      - run: |
          docker create \
            -v /home/circleci/.m2 \
            -v /home/circleci/jackdaw \
            --name data circleci/clojure:lein-2.8.1 \
            /bin/true

          docker cp /home/circleci/.m2 data:/home/circleci/
          docker cp /home/circleci/jackdaw data:/home/circleci/

          docker run \
            --env-file .env.circle \
            --workdir /home/circleci/jackdaw \
            --volumes-from data \
            --network jackdaw_default \
            circleci/clojure:lein-2.8.1 lein test

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - checkout_code
      - deps:
          context: org-global
          requires:
            - checkout_code
      - build:
          context: org-global
          requires:
            - deps
